Feat/add navigation header on layout
KALrious/impact-bridge-front pull request #32
Opened 2023-08-26 17:33 UTC by AntoineBourin

2023-08-26 18:15 UTC, KALrious commented
pour tes remarques :

- Les bons items de menu (j'ai mis que Accueil et Rechercher ?): `search`, `settings`, `message`, un avatar en connecter ou quand on click on peut se déconnecter
- Les bons items de menu (j'ai mis que Accueil et Rechercher ?) oui il y a un boutton connexion et inscription
 
tu peux normalement le faire dans cette US,
pour le logOut normalement c'est dans `next-auth` que c'est géré :)

2023-08-26 21:24 UTC, KALrious requested changes

2023-08-26 21:24 UTC, KALrious commented on next.config.js
> +module.exports = withNextIntl({
ça change rien tes changements ?
tu perds juste le type ?

2023-08-26 21:24 UTC, KALrious commented on src/components/design-system/atoms/burger-icon/burger-icon.tsx
> +      <Disclosure.Button className="relative inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-100 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-inse
Enfaite la main color c'est pirate gold, du coup tu peux remplacer tout les indigo en pirategold ?

```suggestion
      <Disclosure.Button className="relative inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-100 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-inset focus:ring-pirateGold">
```

2023-08-26 21:24 UTC, KALrious commented on src/components/design-system/molecules/navigation-header/mobile-navigation-header.tsx
> +              ? 'border-indigo-500 bg-indigo-50 text-indigo-700'
pour le 700 peut être que tu peux mettre cette couleur:
[#c0ac8c](https://www.color-hex.com/color/c0ac8c)
peut être le rajouter dans la config tailwind ?

2023-08-26 21:24 UTC, KALrious commented on src/components/navigation/navigation.tsx
> +                    { href: '#', label: t('profile') },
je pense que lui tu n'en a pas besoin :)

2023-08-26 21:24 UTC, KALrious commented on src/components/navigation/navigation.tsx
> +  return (
y a moyens que ça puisse utiliser les information de nextAuth ?

2023-08-26 21:24 UTC, KALrious commented on src/components/navigation/navigation.tsx
> +          <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
est-ce que c'est possible de la rendre `position: sticky` ?

2023-08-28 19:00 UTC, AntoineBourin commented on src/components/design-system/atoms/burger-icon/burger-icon.tsx
> +      <Disclosure.Button className="relative inline-flex items-center justify-center rounded-md p-2 text-gray-400 hover:bg-gray-100 hover:text-gray-500 focus:outline-none focus:ring-2 focus:ring-inse
done

2023-08-28 19:00 UTC, AntoineBourin commented on src/components/design-system/molecules/navigation-header/mobile-navigation-header.tsx
> +              ? 'border-indigo-500 bg-indigo-50 text-indigo-700'
done

2023-08-28 19:01 UTC, AntoineBourin commented on src/components/navigation/navigation.tsx
> +  return (
done

2023-08-28 19:01 UTC, AntoineBourin commented on src/components/navigation/navigation.tsx
> +          <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
done

2023-08-28 21:08 UTC, KALrious approved these changes

2023-08-28 21:08 UTC, KALrious commented on src/components/design-system/molecules/profile-header/profile-header.tsx
> +            src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80"
je crois qu'ici tu voulais mettre:
```suggestion
            src={userImage}
```

2023-08-29 12:42 UTC, merged